/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serhiihurin_passwordmanager_connector_DllConnector */

#ifndef _Included_com_serhiihurin_passwordmanager_connector_DllConnector
#define _Included_com_serhiihurin_passwordmanager_connector_DllConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serhiihurin_passwordmanager_connector_DllConnector
 * Method:    USBInfoExtractor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_serhiihurin_passwordmanager_connector_DllConnector_USBInfoExtractor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
