package com.serhiihurin.passwordmanager.views.list;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.html.H4;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;

@PageTitle("Settings")
@Route(value = "settings-view", layout = MainLayout.class)
public class SettingsView extends Composite<VerticalLayout> {

    public SettingsView() {
        H4 h4 = new H4();
        Hr hr = new Hr();
        HorizontalLayout layoutRow = new HorizontalLayout();
        TextField textField = new TextField();
        TextField textField2 = new TextField();
        Button buttonPrimary = new Button();
        Hr hr2 = new Hr();
        H4 h42 = new H4();
        Hr hr3 = new Hr();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        EmailField emailField = new EmailField();
        Button buttonPrimary2 = new Button();
        Hr hr4 = new Hr();
        H4 h43 = new H4();
        Hr hr5 = new Hr();
        Button buttonPrimary3 = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        h4.setText("Basic");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, h4);
        h4.setWidth("max-content");
        layoutRow.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.setHeight("min-content");
        layoutRow.setAlignItems(Alignment.CENTER);
        layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
        textField.setLabel("Name");
        textField.setWidth("min-content");
        textField2.setLabel("Last name");
        layoutRow.setAlignSelf(FlexComponent.Alignment.CENTER, textField2);
        textField2.setWidth("min-content");
        buttonPrimary.setText("Save");
        layoutRow.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary);
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        h42.setText("Change email");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, h42);
        h42.setWidth("max-content");
        layoutRow2.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.setHeight("min-content");
        layoutRow2.setAlignItems(Alignment.CENTER);
        layoutRow2.setJustifyContentMode(JustifyContentMode.CENTER);
        emailField.setLabel("Email");
        emailField.setWidth("min-content");
        buttonPrimary2.setText("Send verification");
        layoutRow2.setAlignSelf(FlexComponent.Alignment.END, buttonPrimary2);
        buttonPrimary2.setWidth("min-content");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        h43.setText("Change token");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, h43);
        h43.setWidth("max-content");
        buttonPrimary3.setText("Unlink USB Token");
        getContent().setAlignSelf(FlexComponent.Alignment.CENTER, buttonPrimary3);
        buttonPrimary3.setWidth("min-content");
        buttonPrimary3.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        getContent().add(h4);
        getContent().add(hr);
        getContent().add(layoutRow);
        layoutRow.add(textField);
        layoutRow.add(textField2);
        layoutRow.add(buttonPrimary);
        getContent().add(hr2);
        getContent().add(h42);
        getContent().add(hr3);
        getContent().add(layoutRow2);
        layoutRow2.add(emailField);
        layoutRow2.add(buttonPrimary2);
        getContent().add(hr4);
        getContent().add(h43);
        getContent().add(hr5);
        getContent().add(buttonPrimary3);
    }
}
